### ISSUE TITLE
Validation setup

### ISSUE THREAD

**Issue by IvanSedykh** [deepmind/code_contests#38]
After reading the paper one thing remains unclear to me.

For some problems in the dataset there are only few private tests. Overall, which solutions do you consider correct -- the ones that passes private+generated tests or only private?

Thanks.

**Comment by felixgimeno** [comment]
for our validation set: needs to pass public+private+generated

because the inputs of generated tests are created via mutation, there is a risk of them being invalid, so the ground truth is still submitting to codeforces, but for the validation set we just check that we pass all the tests we have (public+private+generated)
